### ISSUE TITLE
Copyright and Licensing stripped from source files

### ISSUE THREAD

**Issue by Ninds** [Ninds/Ryu.NET#1]
@ulfjack & @Dogwei 
I have created a repository of a C# implementation of Ryu by initially forking https://github.com/Dogwei/RyuCsharp. 
The C# implementation appears to be a more or less direct line for line conversion from the the C implementation with little intrusive modifications (which is a good thing).
However all copyright and licensing details had been stripped from the source files. Can they/ should they  be re-instated ?

Thanks 
N

**Comment by ulfjack** [comment]
Hi @Ninds, and thanks for letting me know.

I'm not planning to enforce my copyright on Ryu - I want it to be as widely available and useable as possible. If businesses want to use the code, it generally needs to be licensed (this is what I have been told by a lawyer; I am not one and this is not legal advice) - the Apache 2 license is generally perceived to be business-friendly.

I'd also caution you that @Dogwei may or may not have copyright on the code they posted, which they could potentially enforce.

**Comment by Ninds** [comment]
@ulfjack 
Thanks for getting back to me. The  C# code I imported from @Dogwei is essentially a verbatim copy of your C code so if you'd like your copyright & license text reinstated at the top of each source file that would simplify things. Similarly for any changes @Dogwei  has made. 
I have no intention to digress from the license you have chosen for any modifications that I have/will make. 
N

**Comment by Dogwei** [comment]
Hi @Ninds @ulfjack.
Sorry i'm late.
I won’t enforce the copyright of this, I wrote this program just wanna share and learn from each other.

**Comment by Ninds** [comment]
Thanks. 
I'll then add two files with the texts of Apache & Boost OS licences in the Repo.
